image: Visual Studio 2017

branches:
  only:
  - master

# Don't create a build when a PR is opened
skip_branch_with_pr: true

nuget:
  disable_publish_on_pr: true
  
skip_commits:
  files:
    - 'doc/**/*.*'  

init:
- ps: git config --global core.autocrlf true

build_script:
- ps: .\build\build.ps1 -Script build\build.cake

artifacts:
- path: .\build\*.nupkg

test:
  assemblies:
    - '**\*.tests.dll'

deploy:
  provider: NuGet
  api_key:
    secure: 9LJHTUCVmXmveJDJluMddhCyv4CikF1PYlpQLsiN28v2zw8Wh+/IvQzuVk5nfDw1
  skip_symbols: true
  artifact: /.*\.nupkg/